version: '3'
services:

  caddy:
    build:
      context: ../corpscanada-x
      dockerfile: Dockerfile.caddy
    environment:
      TOB_API_URL: ${TOB_API_URL:-}
      WEB_BASE_HREF: ${WEB_BASE_HREF:-/}
      WEB_HOST_NAME: ${WEB_HOST_NAME:-0.0.0.0}
      WEB_HOST_PORT: ${WEB_HOST_PORT:-8080}
      WEB_HOST_TLS: ${WEB_HOST_TLS:-off}
      AGENT_HOST: ${AGENT_HOST:-agent}
      AGENT_PORT: ${AGENT_PORT:-8000}
    links:
      - corpscanada-agent:agent
    networks:
      - vonx
    ports:
      - ${WEB_HTTP_PORT:-5000}:${WEB_HOST_PORT:-8080}
    volumes:
      - caddy-data:/root/.caddy
      - caddy-logs:/srv/logs

  corpscanada-agent:
    build:
      context: ../corpscanada-x
      dockerfile: Dockerfile
    environment:
      APPLICATION_URL: ${APPLICATION_URL:-http://localhost:5000}
      ENDPOINT_URL: ${ENDPOINT_URL:-http://localhost:5001}
      CONFIG_ROOT: ../config
      ENVIRONMENT: ${ENVIRONMENT:-default}
      ENABLE_GUNICORN: ${ENABLE_GUNICORN:-0}
      INDY_LEDGER_URL: ${LEDGER_URL:-http://localhost:9000}
      FORMS: ${FORMS:-}
      ISSUERS: ${ISSUERS:-}
      LOG_LEVEL: ${LOG_LEVEL:-}
      PYTHON_ENV: ${PYTHON_ENV:-development}
      TOB_API_URL: ${TOB_API_URL:-}
      TOB_APP_URL: ${TOB_APP_URL:-}
      WALLET_TYPE: ${WALLET_TYPE}
      POSTGRESQL_WALLET_HOST: ${POSTGRESQL_WALLET_HOST}
      POSTGRESQL_WALLET_PORT: ${POSTGRESQL_WALLET_PORT}
      POSTGRESQL_WALLET_USER: ${POSTGRESQL_USER}
      POSTGRESQL_WALLET_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_WALLET_ADMIN_PASSWORD: ${POSTGRESQL_ADMIN_PASSWORD}
      WALLET_ENCRYPTION_KEY: ${WALLET_ENCRYPTION_KEY}
      INDY_WALLET_SEED: ${INDY_WALLET_SEED:-}
      INDY_WALLET_DID: ${INDY_WALLET_DID}
    networks:
      - orgbook
      - vonx
    depends_on:
      - corpscanada-wallet-db
    entrypoint: >
      /bin/bash -c "
        echo sleeping ...;
        sleep 15;
        ../docker-entrypoint.sh;"

  corpscanadamara:
    build:
      context: ../data-pipeline
      dockerfile: docker/mara-app/Dockerfile
    environment:
      # web hooks
      - ENVIRONMENT=${ENVIRONMENT:-default}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_LEVEL=${WEBHOOK_LEVEL:-0}  # 0=Error, 1=Warning, 2=Info
      - PROJECT_NAME=${PROJECT_NAME:-von-local-developer-agent}
      - FRIENDLY_PROJECT_NAME=${FRIENDLY_PROJECT_NAME:-Local Developer Data Pipeline}
      - VONX_API_URL=${VONX_API_URL:-http://corpscanada-agent:8000/corpscanada}
      # [gc_registries]
      - CORPSCANADA_DB_HOST=${CORPSCANADA_DB_HOST:-host.docker.internal}
      - CORPSCANADA_DB_PORT=${CORPSCANADA_DB_PORT:-5454}
      - CORPSCANADA_DB_DATABASE=${CORPSCANADA_DB_DATABASE:-CORPORATION_CANADA}
      - CORPSCANADA_DB_USER=${CORPSCANADA_DB_USER}
      - CORPSCANADA_DB_PASSWORD=${CORPSCANADA_DB_PASSWORD}
      # [event_processor]
      - EVENT_PROC_DB_HOST=${EVENT_PROC_DB_HOST:-corpscanadadb}
      - EVENT_PROC_DB_PORT=${EVENT_PROC_DB_PORT:-5432}
      - EVENT_PROC_DB_DATABASE=${EVENT_PROC_DB_DATABASE:-corpscanada_db}
      - EVENT_PROC_DB_USER=${EVENT_PROC_DB_USER:-corpscanada_db}
      - EVENT_PROC_DB_PASSWORD=
      # [mara_db]
      - MARA_DB_HOST=${MARA_DB_HOST:-corpscanadadb}
      - MARA_DB_PORT=${MARA_DB_PORT:-5432}
      - MARA_DB_DATABASE=${MARA_DB_DATABASE:-mara_db}
      - MARA_DB_USER=${MARA_DB_USER:-mara_db}
      # orgbook DB
      - ORGBOOK_DB_HOST=${ORGBOOK_DB_HOST:-tob-db}
      - ORGBOOK_DB_PORT=${ORGBOOK_DB_PORT:-5432}
      - ORGBOOK_DB_DATABASE=${ORGBOOK_DB_DATABASE:-THE_ORG_BOOK}
      - ORGBOOK_DB_USER=${ORGBOOK_DB_USER:-DB_USER}
      - ORGBOOK_DB_PASSWORD=${ORGBOOK_DB_PASSWORD:-DB_PASSWORD}
    networks:
      - orgbook
    ports:
      - "5050:5000"
    depends_on:
      - corpscanadadb
    entrypoint: >
      /bin/bash -c "
        echo sleeping ...;
        sleep 5;
        ./docker-entrypoint.sh;"

  corpscanadadb:
    build:
      context: ../data-pipeline
      dockerfile: docker/postgres/Dockerfile
    environment:
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
    networks:
      - orgbook
    ports:
      #- 5432:5432
      - 5444:5432
    volumes:
      - mara-data:/var/lib/pgsql/data

  corpscanada-wallet-db:
    image: registry.access.redhat.com/rhscl/postgresql-95-rhel7:9.5
    environment:
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_ADMIN_PASSWORD=${POSTGRESQL_ADMIN_PASSWORD}
    networks:
      - orgbook
    ports:
      - 5434:5432
    volumes:
      - wallet-db:/var/lib/pgsql/data

volumes:
  caddy-data:
  caddy-logs:
  mara-data:
  wallet-db:

networks:
  vonx:
  orgbook:
    external:
      name: tob_tob


