version: '3'
services:
  #
  # corpscanadamara
  #
  corpscanadamara:
    image: maraapp
    environment:
      - VONX_API_URL=${VONX_API_URL:-http://corpscanada-agent:8000/corpscanada}
      # [corpscanadaistries]
      - CORPSCANADA_DB_HOST=${CORPSCANADA_DB_HOST:-host.docker.internal}
      - CORPSCANADA_DB_PORT=${CORPSCANADA_DB_PORT:-5454}
      - CORPSCANADA_DB_DATABASE=${CORPSCANADA_DB_DATABASE:-CORPSCANADAISTRIES}
      - CORPSCANADA_DB_USER=${CORPSCANADA_DB_USER}
      - CORPSCANADA_DB_PASSWORD=${CORPSCANADA_DB_PASSWORD}
      # [event_processor]
      - EVENT_PROC_DB_HOST=${EVENT_PROC_DB_HOST:-corpscanadadb}
      - EVENT_PROC_DB_PORT=${EVENT_PROC_DB_PORT:-5432}
      - EVENT_PROC_DB_DATABASE=${EVENT_PROC_DB_DATABASE:-corpscanada_db}
      - EVENT_PROC_DB_USER=${EVENT_PROC_DB_USER:-corpscanada_db}
      - EVENT_PROC_DB_PASSWORD=
      # [mara_db]
      - MARA_DB_HOST=${MARA_DB_HOST:-corpscanadadb}
      - MARA_DB_DATABASE=${MARA_DB_DATABASE:-mara_db}
      - MARA_DB_USER=${MARA_DB_USER:-mara_db}
    networks:
      - orgbook
    ports:
      - "5050:5000"
    depends_on:
      - corpscanadadb
    command: >
      /bin/bash -c "
        echo sleeping ...;
        sleep 5;
        cd data-pipeline/;
        make;
        source .venv/bin/activate;
        flask run --host=0.0.0.0 --with-threads --reload --eager-loading;"

  #
  # corpscanadadb
  #
  corpscanadadb:
    image: maradb
    environment:
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
    networks:
      - orgbook
    ports:
      #- 5432:5432
      - 5444:5432
    volumes:
      - mara-data:/var/lib/pgsql/data

networks:
  orgbook:
    external:
      name: tob_tob

volumes:
  mara-data:


